name: Create GitHub Issue and Notion Database Page
on:
  workflow_dispatch:
jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.create-issue.outputs.issue-number }}
    steps:
      - name: Create Issue
        id: create-issue
        uses: imjohnbo/issue-bot@v3
        with:
          title: 'Awesome title here'
          labels: "development"
          body: |
            Awesome body here.
  create-notion-page:
    runs-on: ubuntu-latest
    needs: create-issue
    name: Create Notion Page
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Notion Page
        uses: ./
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        with:
          title: 'Awesome title here'
          category: "development"
          issue-number: ${{ needs.create-issue.outputs.issue-number }}
